name: pyssm
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake
  - python=3.8
  - numpy
  - pip
  - pandas
  - scipy
  - plotly # Technically not a dependency, but still nice to have for browsing results
  - plotly-orca # Technically not a dependency, but still nice to have for browsing results
  - psutil # Technically not a dependency, but required for exporting PDFs from plotting
  - jupyter # Technically not a dependency, but still nice to have for browsing results
  - pip:
    - pylint
    - plotly-express
    - nbformat
    - torch # for processing Stream51
    - torchvision # for processing Stream51
    - kaggle # for downloading creditfraud dataset
    - gdown # for downloading the Stream51 dataset from google drive
    - spacy # for processing the examiner and abc datasets
    - pyfact # for downloading / processing fact data
    - progressbar
  #  - -e file:. 
