name: C++ tests

on:
  push:
    branches: [master]

jobs:
  test-cpp:
    runs-on: "ubuntu-latest"
    name: Test cpp code
    #shell: bash -l {0}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: pyssm
          environment-file: environment.yml
      - name: Test CPP Code
        run: |
          cd build
          cmake ..
          make
          ./main